# Generated by Django 4.1 on 2022-08-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_location_lat_alter_location_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
