# Generated by Django 4.1 on 2022-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
